### ISSUE TITLE
Implement code of use model

### ISSUE THREAD

**Issue by Valwolfor** [Home-Group-05-IA-Assignment/AI-Fellowship#5]
Bert model is okay.

**Comment by Valwolfor** [comment]
We need implement models trained by @JcortesJ

**Comment by JcortesJ** [comment]
LogisticRegression model was uploaded in LogisticModel.pkl. It was also used s second model for the vectorization and characteristics extractions, which is called tfidvectorizer.pkl.

Those two models are implemented in preprocessorLog.py and logisticModel.py. Their input is a .txt file and their output is a DataFrame with the 6 emotions and their probability in all the text. It might be also exported in a .csv
